import Head from 'next/head';
import { Incident, IncidentDao, safeStringify } from 'util/db';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home({ items }: { items: Incident[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>XDaysSince</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>XDaysSince</h1>

        <ul>
          {items.map((item) => (
            <li key={item._id.toString()}>
              <Link href={`/i/${item._id}`}>
                <a>{item.title}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const items = await IncidentDao.getAll();
  return {
    props: { items: safeStringify(items) },
  };
}
