import Head from 'next/head';
import { Incident, IncidentDao, safeStringify } from 'lib/db';
import styles from '../styles/Home.module.css';
import { IncidentItem } from 'components/IncidentItem';

export default function Home({ items }: { items: Incident[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>XDaysSince</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>XDaysSince</h1>

        <ul>
          {items.map((item) => (
            <IncidentItem key={item._id.toString()} item={item} />
          ))}
        </ul>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const items = await IncidentDao.getAll();
  return {
    props: { items: safeStringify(items) },
  };
}
